import { useEffect, useState } from "react";

const DISCLAIMER_KEY = "aignited-disclaimer-accepted";

export function useDisclaimer() {
	const [accepted, setAccepted] = useState(() => {
		return localStorage.getItem(DISCLAIMER_KEY) === "true";
	});

	function accept() {
		localStorage.setItem(DISCLAIMER_KEY, "true");
		setAccepted(true);
	}

	return { accepted, accept };
}

interface DisclaimerProps {
	onAccept: () => void;
}

export function Disclaimer({ onAccept }: DisclaimerProps) {
	useEffect(() => {
		function handleKey(e: KeyboardEvent) {
			if (e.key === "Enter") onAccept();
		}
		window.addEventListener("keydown", handleKey);
		return () => window.removeEventListener("keydown", handleKey);
	}, [onAccept]);

	return (
		<div
			role="presentation"
			className="fixed inset-0 z-50 flex items-center justify-center bg-black/70"
		>
			<div
				role="dialog"
				aria-modal="true"
				className="w-full max-w-xl rounded border border-t-border bg-t-surface p-6 mx-4"
			>
				<h2 className="mb-4 font-mono text-sm font-medium text-t-amber">
					Disclaimer & Terms of Use
				</h2>

				<div className="space-y-3 text-xs leading-relaxed text-t-text-secondary max-h-[60vh] overflow-y-auto pr-2">
					<p>
						<span className="font-medium text-t-text">Not Financial Advice (NFA)</span> — All data,
						analysis, scores, signals, and indicators displayed on AIgnited Terminal are for
						educational and informational purposes only. Nothing on this platform constitutes
						financial advice, investment advice, trading advice, or any other kind of professional
						advice.
					</p>

					<p>
						<span className="font-medium text-t-text">Do Your Own Research (DYOR)</span> — You are
						solely responsible for evaluating the information presented and making your own
						independent decisions. Always conduct your own due diligence before making any
						investment or trading decision.
					</p>

					<div>
						<span className="font-medium text-t-text">No Liability</span> — The creator(s) and
						developer(s) of AIgnited Terminal shall not be held responsible or liable for:
						<ul className="mt-1.5 ml-4 list-disc space-y-1 text-t-text-muted">
							<li>
								Any financial losses, damages, or consequences arising from the use of this tool
							</li>
							<li>The accuracy, completeness, or timeliness of any data or analysis</li>
							<li>Any decisions made based on the information presented</li>
							<li>Any technical errors, interruptions, or data discrepancies</li>
						</ul>
					</div>

					<p>
						<span className="font-medium text-t-text">Risk Acknowledgment</span> — Stock trading and
						investing involve substantial risk of loss. Past performance does not guarantee future
						results. Scores and signals generated by this tool are based on computational models
						that may be inaccurate or misleading.
					</p>

					<p className="text-t-text-muted italic">
						By proceeding, you acknowledge that all investment decisions are made at your own risk
						and discretion.
					</p>
				</div>

				<div className="mt-5 border-t border-t-border pt-4">
					<button
						type="button"
						onClick={onAccept}
						className="w-full rounded border border-t-green/30 bg-t-green/10 px-4 py-2 font-mono text-xs font-medium text-t-green transition-colors hover:bg-t-green/20"
					>
						I have read and understood this disclaimer. I agree that the creator is not responsible
						for any implications from the data or any decisions I make based on this tool.
					</button>
					<p className="mt-2 text-center font-mono text-[10px] text-t-text-muted">
						Press Enter to accept
					</p>
				</div>
			</div>
		</div>
	);
}
